// packages/react-core/workspace-setup-react/src/ImportConfig.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
declare const fin: any;

import { useState, useRef, useEffect } from "react";
// /config subpath — side-effect-free; safe in plain-browser dev contexts.
import {
  importConfigBundle,
  IAB_RELOAD_AFTER_IMPORT,
  IAB_REGISTRY_CONFIG_UPDATE,
  type ImportConfigBundleResult,
} from "@starui/openfin-platform/config";
import { UPLOAD_SVG } from "@starui/icons-svg/all-icons";
import { spacing, typography } from "@starui/design-system/tokens";
import { Input } from "@starui/ui";

// ─── Types ───────────────────────────────────────────────────────────

type ImportStatus = "idle" | "success" | "error";

// ─── Design tokens ───────────────────────────────────────────────────
// Maps to the --de-* editor design system from @starui/design-system.
// This component always renders in dark mode (utility dialog).
const COLORS = {
  accent:        "var(--de-accent)",
  danger:        "var(--de-danger)",
  success:       "var(--de-success)",
  bg:            "var(--de-bg-deep)",
  surface:       "var(--de-bg-surface)",
  border:        "var(--de-border-strong)",
  textPrimary:   "var(--de-text)",
  textSecondary: "var(--de-text-secondary)",
};

// ─── Helpers ─────────────────────────────────────────────────────────

/** Returns true when the app is running inside an OpenFin window. */
const isInOpenFin = typeof (window as any).fin !== "undefined";

// ─── Component ───────────────────────────────────────────────────────

/**
 * ImportConfig — hosted in a small OpenFin window at /import-config.
 *
 * Lets the user upload a JSON file previously exported via "Export Config".
 * On successful import it reloads the dock and closes this window.
 */
export default function ImportConfig() {
  const [status, setStatus] = useState<ImportStatus>("idle");
  const [fileName, setFileName] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const closeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Cleanup: clear the auto-close timer if component unmounts early
  useEffect(() => {
    return () => {
      if (closeTimerRef.current) clearTimeout(closeTimerRef.current);
    };
  }, []);

  // ── Handle file selection ─────────────────────────────────────────

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setStatus("idle");
    setMessage("");

    try {
      const text = await file.text();
      const importData = JSON.parse(text);

      // Validate: the exported JSON must have an "appConfig" array.
      // This is the shape produced by the "Export Config" action.
      if (!importData.appConfig || !Array.isArray(importData.appConfig)) {
        setStatus("error");
        setMessage("No config data found in this file. Make sure it is a valid config export.");
        return;
      }

      // Bulk-import every supported section. The helper re-owns appConfig
      // rows (rewrites appId/userId to the local host environment) so
      // workspaces, registries, and per-instance markets-grid-profile-set
      // rows — including the `gridLevelData` that carries data-provider
      // selection — become readable on this machine. userProfile rows are
      // intentionally excluded from auto-import (see `importConfigBundle`).
      const result = await importConfigBundle(importData);

      if (result.totalImported === 0) {
        setStatus("error");
        setMessage("No importable rows found in this file.");
        return;
      }

      // Notify other surfaces. IAB_RELOAD_AFTER_IMPORT prompts the dock
      // provider window to reload its buttons; IAB_REGISTRY_CONFIG_UPDATE
      // tells the registry editor / launchers to re-read the registry.
      if (isInOpenFin) {
        const iab = (window as any).fin.InterApplicationBus;
        await iab.publish(IAB_RELOAD_AFTER_IMPORT, {});
        if (result.appConfig.imported > 0) {
          await iab.publish(IAB_REGISTRY_CONFIG_UPDATE, {});
        }
      }

      setStatus("success");
      setMessage(formatSuccessMessage(result));

      // Auto-close after 1.5 s so the user can read the success message
      closeTimerRef.current = setTimeout(async () => {
        if (isInOpenFin) {
          await (window as any).fin.Window.getCurrentSync().close();
        }
      }, 1500);
    } catch (err) {
      console.error("Import failed:", err);
      setStatus("error");
      setMessage("Failed to read the file. Make sure it is a valid config export.");
    }
  }

  function formatSuccessMessage(r: ImportConfigBundleResult): string {
    const parts: string[] = [];
    if (r.appConfig.imported)   parts.push(`${r.appConfig.imported} config row${r.appConfig.imported === 1 ? '' : 's'}`);
    if (r.appRegistry.imported) parts.push(`${r.appRegistry.imported} app${r.appRegistry.imported === 1 ? '' : 's'}`);
    if (r.roles.imported)       parts.push(`${r.roles.imported} role${r.roles.imported === 1 ? '' : 's'}`);
    if (r.permissions.imported) parts.push(`${r.permissions.imported} permission${r.permissions.imported === 1 ? '' : 's'}`);
    const summary = parts.length > 0 ? `Imported ${parts.join(', ')}.` : 'Import complete.';
    return r.totalFailed > 0
      ? `${summary} ${r.totalFailed} row${r.totalFailed === 1 ? '' : 's'} failed — see console for details.`
      : summary;
  }

  // ── Render ───────────────────────────────────────────────────────
  // Destructure COLORS for convenience in JSX
  const { accent: accentColor, danger: dangerColor, success: successColor,
          bg, surface, border, textPrimary, textSecondary } = COLORS;

  return (
    <div style={{
      position: "fixed", inset: 0,
      background: bg, color: textPrimary,
      fontFamily: "var(--ds-font-sans)",
      display: "flex", flexDirection: "column",
      alignItems: "center", justifyContent: "center",
      gap: spacing[6], padding: spacing[8],
    }}>
      {/* Icon */}
      <div style={{
        width: 56, height: 56, borderRadius: "var(--de-radius-lg)",
        background: surface, border: `1px solid ${border}`,
        display: "flex", alignItems: "center", justifyContent: "center",
      }}>
        <div
          style={{ width: 28, height: 28, color: accentColor }}
          dangerouslySetInnerHTML={{
            __html: UPLOAD_SVG
              .replace(/width="24"/, 'width="28"')
              .replace(/height="24"/, 'height="28"')
              .replace(/stroke-width="2"/, 'stroke-width="1.8"'),
          }}
        />
      </div>

      {/* Title */}
      <div style={{ textAlign: "center" }}>
        <h1 style={{
          fontSize: typography.fontSize.lg,
          fontWeight: typography.fontWeight.semibold,
          margin: 0,
          color: textPrimary,
        }}>
          Import Config
        </h1>
        <p style={{
          fontSize: typography.fontSize.md,
          color: textSecondary,
          margin: `${spacing[1.5]}px 0 0`,
        }}>
          Select a previously exported config JSON file
        </p>
      </div>

      {/* Drop zone / file button */}
      <div
        onClick={() => fileInputRef.current?.click()}
        style={{
          width: "100%", maxWidth: 320,
          border: `1.5px dashed ${fileName ? accentColor : border}`,
          borderRadius: "var(--de-radius-md)",
          padding: `${spacing[5]}px ${spacing[4]}px`,
          textAlign: "center", cursor: "pointer",
          background: fileName ? `${accentColor}10` : surface,
          transition: "all 0.15s",
        }}
        onMouseEnter={e => { e.currentTarget.style.borderColor = accentColor; e.currentTarget.style.background = `${accentColor}10`; }}
        onMouseLeave={e => {
          if (!fileName) {
            e.currentTarget.style.borderColor = border;
            e.currentTarget.style.background = surface;
          }
        }}
      >
        {fileName ? (
          <span style={{
            fontSize: typography.fontSize.md,
            color: accentColor,
            fontWeight: typography.fontWeight.medium,
          }}>
            {fileName}
          </span>
        ) : (
          <span style={{ fontSize: typography.fontSize.md, color: textSecondary }}>
            Click to select a <strong style={{ color: textPrimary }}>.json</strong> file
          </span>
        )}
      </div>

      <Input
        ref={fileInputRef}
        type="file"
        accept=".json"
        className="hidden"
        onChange={handleFileChange}
      />

      {/* Status message */}
      {message && (
        <p style={{
          fontSize: typography.fontSize.md,
          textAlign: "center",
          margin: 0,
          color: status === "success" ? successColor : dangerColor,
        }}>
          {message}
        </p>
      )}

      {/* Close button */}
      <button
        onClick={async () => {
          if (isInOpenFin) {
            await (window as any).fin.Window.getCurrentSync().close();
          }
        }}
        style={{
          padding: `${spacing[2]}px ${spacing[6]}px`,
          fontSize: typography.fontSize.md,
          fontWeight: typography.fontWeight.medium,
          border: `1px solid ${border}`, borderRadius: "var(--de-radius-sm)",
          background: "transparent", color: textSecondary,
          cursor: "pointer", transition: "all 0.12s",
        }}
        onMouseEnter={e => { e.currentTarget.style.borderColor = textSecondary; e.currentTarget.style.color = textPrimary; }}
        onMouseLeave={e => { e.currentTarget.style.borderColor = border; e.currentTarget.style.color = textSecondary; }}
      >
        Cancel
      </button>
    </div>
  );
}

// packages/dock-editor-angular/src/import-config/import-config.component.ts
/**
 * ImportConfigComponent
 *
 * Angular equivalent of the React ImportConfig component.
 * Hosted in a small OpenFin window at /import-config.
 * Lets the user upload a JSON config exported via "Export Config".
 */

import { Component, signal, ChangeDetectionStrategy, DestroyRef, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ButtonModule } from 'primeng/button';
import {
  importConfigBundle,
  IAB_RELOAD_AFTER_IMPORT,
  IAB_REGISTRY_CONFIG_UPDATE,
  type ImportConfigBundleResult,
} from '@marketsui/openfin-platform';

type ImportStatus = 'idle' | 'success' | 'error';

const isInOpenFin = typeof (window as any).fin !== 'undefined';

@Component({
  selector: 'mkt-import-config',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, ButtonModule],
  template: `
    <div data-dock-editor
      class="fixed inset-0 flex flex-col items-center justify-center gap-6 p-8"
      style="background: var(--de-bg-deep); color: var(--de-text); font-family: var(--de-font);"
    >
      <!-- Icon -->
      <div
        class="w-14 h-14 flex items-center justify-center"
        style="background: var(--de-bg-surface); border: 1px solid var(--de-border-strong);
               border-radius: var(--de-radius-lg);"
      >
        <i class="pi pi-upload" style="font-size: 24px; color: var(--de-accent);"></i>
      </div>

      <!-- Title -->
      <div class="text-center">
        <h1 class="text-lg font-semibold m-0" style="color: var(--de-text);">Import Config</h1>
        <p class="m-0 mt-1" style="color: var(--de-text-secondary); font-size: 13px;">
          Select a previously exported config JSON file
        </p>
      </div>

      <!-- Drop zone — max-width 320px to match React -->
      <div
        class="w-full p-5 text-center cursor-pointer transition-all"
        [style.border]="'1.5px dashed ' + (fileName() ? 'var(--de-accent)' : 'var(--de-border-strong)')"
        [style.background]="fileName() ? 'var(--de-accent-dim)' : 'var(--de-bg-surface)'"
        style="border-radius: var(--de-radius-md); max-width: 320px;"
        (click)="fileInput.click()"
      >
        <span style="font-size: 13px;" [style.color]="fileName() ? 'var(--de-accent)' : 'var(--de-text-secondary)'">
          {{ fileName() ?? 'Click to select a .json file' }}
        </span>
      </div>
      <input
        #fileInput
        type="file"
        accept=".json"
        class="hidden"
        (change)="onFileChange($event)"
      />

      <!-- Status message -->
      <p
        *ngIf="message()"
        class="text-center m-0"
        style="font-size: 13px;"
        [style.color]="status() === 'success' ? 'var(--de-success)' : 'var(--de-danger)'"
      >
        {{ message() }}
      </p>

      <!-- Cancel -->
      <p-button
        label="Cancel"
        severity="secondary"
        (onClick)="close()"
      />
    </div>
  `,
})
export class ImportConfigComponent {
  private readonly destroyRef = inject(DestroyRef);

  protected readonly status   = signal<ImportStatus>('idle');
  protected readonly fileName = signal<string | null>(null);
  protected readonly message  = signal('');

  private closeTimer: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    this.destroyRef.onDestroy(() => {
      if (this.closeTimer !== null) {
        clearTimeout(this.closeTimer);
      }
    });
  }

  protected async onFileChange(event: Event): Promise<void> {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;

    this.fileName.set(file.name);
    this.status.set('idle');
    this.message.set('');

    try {
      const text = await file.text();
      const importData = JSON.parse(text);

      if (!importData.appConfig || !Array.isArray(importData.appConfig)) {
        this.status.set('error');
        this.message.set('No config data found in this file. Make sure it is a valid config export.');
        return;
      }

      // Bulk-import every supported section. The helper re-owns appConfig
      // rows (rewrites appId/userId to the local host environment) so
      // workspaces, registries, and per-instance markets-grid-profile-set
      // rows — including the `gridLevelData` that carries data-provider
      // selection — become readable on this machine. userProfile rows are
      // intentionally excluded from auto-import.
      const result = await importConfigBundle(importData);

      if (result.totalImported === 0) {
        this.status.set('error');
        this.message.set('No importable rows found in this file.');
        return;
      }

      if (isInOpenFin) {
        const iab = (window as any).fin.InterApplicationBus;
        await iab.publish(IAB_RELOAD_AFTER_IMPORT, {});
        if (result.appConfig.imported > 0) {
          await iab.publish(IAB_REGISTRY_CONFIG_UPDATE, {});
        }
      }

      this.status.set('success');
      this.message.set(this.formatSuccessMessage(result));

      this.closeTimer = setTimeout(() => this.close(), 1500);
    } catch (err) {
      console.error('ImportConfigComponent: Import failed.', err);
      this.status.set('error');
      this.message.set('Failed to read the file. Make sure it is a valid config export.');
    }
  }

  protected close(): void {
    if (isInOpenFin) {
      (window as any).fin.Window.getCurrentSync().close();
    }
  }

  private formatSuccessMessage(r: ImportConfigBundleResult): string {
    const parts: string[] = [];
    if (r.appConfig.imported)   parts.push(`${r.appConfig.imported} config row${r.appConfig.imported === 1 ? '' : 's'}`);
    if (r.appRegistry.imported) parts.push(`${r.appRegistry.imported} app${r.appRegistry.imported === 1 ? '' : 's'}`);
    if (r.roles.imported)       parts.push(`${r.roles.imported} role${r.roles.imported === 1 ? '' : 's'}`);
    if (r.permissions.imported) parts.push(`${r.permissions.imported} permission${r.permissions.imported === 1 ? '' : 's'}`);
    const summary = parts.length > 0 ? `Imported ${parts.join(', ')}.` : 'Import complete.';
    return r.totalFailed > 0
      ? `${summary} ${r.totalFailed} row${r.totalFailed === 1 ? '' : 's'} failed — see console for details.`
      : summary;
  }
}
